blog/urls.py
from django.urls import path

from .views import (BlogHomeView, 
                    PostDetailView, 
                    PostCreate, 
                    BlogListView, 
                    ArchivesListView,
                    PostDeleteView, 
                    PostUpdateView)
from . import views

app_name='blog'


urlpatterns = [
    path('subscribe/', views.subscribe, name='subs'),
    path('search/', views.search_results, name='search_results'),

    path('comment/edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('comment/delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),

    path('archives/<int:year>/', ArchivesListView.as_view(), name='archives_list'),
    path('', BlogHomeView.as_view(), name='blog_home'),
    path('tag/<str:tag>/', BlogListView.as_view(), name='blog_list'),

    path('detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('add_post/', PostCreate.as_view(), name='add_post'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete_post'),
    path('update/<slug:slug>/', PostUpdateView.as_view(), name='update_post'),
]

blog/models.py
from django.db import models
from django.utils import timezone

from django.utils.text import slugify
from profiles.models import Profile

from user.models import User


TAG_CHOICES = [
        ('Research', 'Research'),
        ('News', 'News'),
        ('Games', 'Games'),
        ('Technology', 'Technology'),
        ('Health', 'Health'),
        ('Science', 'Science'),
        ('Enviroment', 'Enviroment'),
        ('Physics', 'Physics'),
        ('Earth', 'Earth'),
]



class Post(models.Model):
    title = models.CharField(max_length=200)
    sub_title = models.CharField(max_length=200)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    content = models.TextField()
    tag = models.CharField(choices=TAG_CHOICES, max_length=15)
    image = models.ImageField(upload_to='post/')
    social = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.title[:50])
            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug=slugify(self.title) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    approved_com = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
            app_label = 'blog'
            
    def __str__(self):
        return f'{self.author} - {self.text}' 

blog/forms.py
from django import forms

from .models import Comment, Post, TAG_CHOICES



class AddPostForm(forms.Form):
    title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Title"}))
    sub_title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Sub title"}))
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Content"}))
    tag = forms.ChoiceField(choices=TAG_CHOICES)
    social = forms.CharField(max_length=50, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Social"}))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={"class": "form-control-file"}))
    
    def save(self, author, **kwargs):
        data = self.cleaned_data
        title = data['title']
        sub_title = data['sub_title']
        content = data['content']
        tag = data['tag']
        social = data['social']
        image = data['image']
        
        # Create and save the data
        author_profile = author.profile  # Assuming there's a one-to-one relationship between User and Profile models
        obj = Post(image=image, title=title, sub_title=sub_title, author=author_profile, content=content, tag=tag, social=social)
        obj.save(**kwargs)



class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [ 'title', 'sub_title', 'content', 'tag', 'social', 'image']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Your Comment', 'rows': 4}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ 'text']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Your Comment', 'rows': 4}),
        }
    


class CommentEditForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }

blog/views.py
import random

from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import DateTimeField
from django.db.models.functions import TruncMonth
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin, FormView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage
from django.urls import reverse
from django.views.generic import ListView, DetailView, DeleteView, UpdateView

from .forms import AddPostForm, CommentForm, CommentEditForm, EditPostForm
from .models import Post, Comment
from user.models import User



@login_required
def subscribe(request):
    # Get the email address from the authenticated user (you may modify this based on your implementation)
    email = request.user.email
    
    # Create and send the subscription email
    subject = 'Subscription Confirmation'
    message = f'Thank you for subscribing! You will now receive updates via email.'
    from_email = 'viktor.05040504@gmail.com'
    to_email = [email]

    email_message = EmailMessage(subject, message, from_email, to_email)
    email_message.send()

    # Redirect back to the home page or any other desired page
    return redirect(reverse('home'))



@login_required
def search_results(request):
    query = request.GET.get('query')
    if query:
        results = Post.objects.filter(title__icontains=query)
    else:
        results = []
    return render(request, 'blog/search_results.html', {'results': results, 'query': query})



@login_required
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    #import pdb;pdb.set_trace()
    if request.method == 'POST':
        form = CommentEditForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('blog:blog_detail', slug=comment.post.slug)
    else:
        form = CommentEditForm(instance=comment)
    return render(request, 'blog/comment_edit.html', {'form': form, 'comment': comment})



@login_required
def comment_delete(request, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    # Add your logic for deleting the comment
    if request.method == 'POST':
        # Delete the comment
        comment.delete()
        messages.success(request, 'Comment deleted successfully.')
        return redirect('blog:blog_detail', slug=comment.post.slug)
    return render(request, 'blog/comment_delete.html', {'comment': comment})



class PostCreate(LoginRequiredMixin, FormView):
    form_class = AddPostForm
    template_name = 'blog/add_post.html'
    success_url = reverse_lazy('blog:blog_home')
    
    def form_valid(self, form, **kwargs):
        form.save(author=self.request.user,  **kwargs)
        return super().form_valid(form)



class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/update_post.html'
    form_class = EditPostForm
    
    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'slug': self.object.slug})


class ArchivesListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/blog_archives.html'
    context_object_name = 'posts'
    
    def get(self, request, year):
        posts = Post.objects.filter(created_at__year=year)
        context = {'year': year, 'posts': posts}
        #import pdb;pdb.set_trace()
        return render(request, 'blog/blog_archives.html', context)



class BlogListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts'
    
    def get_queryset(self):
        tag = self.kwargs.get('tag')
        queryset = super().get_queryset()
        filtered_posts = queryset.filter(tag=tag)
        
        return filtered_posts



class BlogHomeView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/blog_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        posts = Post.objects.all()
        random_post = random.choice(posts)
        context['post'] = random_post
        
        #Get the first post of all times
        context['older_post'] = Post.objects.order_by('-created_at').last()
        #Get me the last post
        context['recent_post'] = Post.objects.order_by('created_at').last()

        context['news_posts'] = Post.objects.order_by('created_at')[:6]
        #import pdb;pdb.set_trace()

        context['authors'] = User.objects.all()

        filtered_objects = Post.objects.annotate(month_year=TruncMonth('created_at', output_field=DateTimeField())).values('month_year').distinct().order_by('month_year')
        
        context['filtered_objects']= filtered_objects

        
        return context



class PostDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = Post
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post_detail'
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'slug': self.object.slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            # Process the form data
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.post = self.object
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)



class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = '/blog/'

templates/blog/add_post.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
    <div class='form'> 
    <h1>Create a new post.</h1>
    <form method="POST" action="{% url 'blog:add_post' %}" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
    </div>
</main>
{% endblock %}

templates/blog/blog_archives.html
{% extends 'base.html' %}
{% block content %}
<main class="container">   
    <h1>Posts for Year {{ year }}</h1>

    {% if posts %}
      <ul>
        {% for post in posts %}
          <a href="{% url 'blog:blog_detail' post.slug %}" style="color: #000; text-decoration: none;" >   
            <li>{{ post.title }} </li> 
          </a>
        {% endfor %}
      </ul>
    {% else %}
      <p>No posts found for the selected year.</p>
    {% endif %}
</main> 
{% endblock %}

templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
  .text-left {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      justify-content: center;
      height: 40vh;
      margin-top: -70px;
  }

  .comment-container {
  display: flex;
  align-items: center;
}

.comment-links {
  margin-left: left;
}

.comment-links a {
  margin-left: 10px;
}

</style>

<main class="container">
    <div class="row g-5">
        <div class="col-md-8">    
          <article class="blog-post">
            <h2 class="blog-post-title">{{post_detail.title}}</h2>
            <br>
            <h4>{{post_detail.sub_title}}</h4>
            <p class="blog-post-meta"> Posten on: {{post_detail.created_at}} Writen by: <a href="#" style="color: black; text-decoration: none;">{{post_detail.author}}</a> | <a href="", style="color: black; text-decoration: none;">{{post_detail.tag}}</a></p>
            <hr>
            <p>{{post_detail.content}}</p>
            {% if post_detail.image.url %}
                <div>
                  
                  <!-- Delete icon for post -->
                  {% if user.is_authenticated and user == post_detail.author.user %}
                    <div style="text-align: right;">
                      <a  href="{% url 'blog:delete_post' post_detail.slug %}" style="color: black; text-decoration:none">
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                        </svg>
                      </a>

                      <a href="{% url 'blog:update_post' post_detail.slug %}" style="margin-left: 15px;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                      </a>
                    </div>

                    <!-- Edit icon for post -->
                    
                  {% endif %}
                </div>
              <img src="{{post_detail.image.url}}" width="100%" height="100%" alt="">
            {% endif %}
            <br>
            
            {% for comment in post_detail.comments.all %}
            <div class="comment-container">
              <p style="margin-top: 10px;" >{{ comment.author }}: {{ comment.text }}</p>
              {% if user.is_authenticated and user == comment.author %}
                <div class="comment-links">
                  <!-- Edit comment -->
                  <a href="{% url 'blog:comment_edit' comment.pk %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                  </a>

                  <!-- Delete comment -->
                  <a href="{% url 'blog:comment_delete' comment.pk %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                      <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                    </svg>
                  </a>
                </div>
              {% endif %}
            </div>
            {% endfor %}

            <!-- Comment Form -->
            <div style="margin-top: 20px; padding-bottom: 20px;">
              <h2>Agrega un comentario</h2>
              <form method="post" class="text-left">
                {% csrf_token %}
                <div class="form-group">
                  <label for="{{ form.text.id_for_label }}"></label>
                  {{ form.text }}
                </div>
                <button type="submit">Submit</button>
              </form>
            </div>
            
            <!-- <blockquote class="blockquote">
              <p>Quoted text goes here.</p>
            </blockquote>
            
            <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
            <h3>Example lists</h3>
            <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout. This is an example unordered list:</p>
            <ul>
              <li>First list item</li>
              <li>Second list item with a longer description</li>
              <li>Third list item to close it out</li>
            </ul>
            <p>And this is an ordered list:</p>
            <ol>
              <li>First list item</li>
              <li>Second list item with a longer description</li>
              <li>Third list item to close it out</li>
            </ol>
            <p>And this is a definiton list:</p>
            <dl>
              <dt>HyperText Markup Language (HTML)</dt>
              <dd>The language used to describe and define the content of a Web page</dd>
              <dt>Cascading Style Sheets (CSS)</dt>
              <dd>Used to describe the appearance of Web content</dd>
              <dt>JavaScript (JS)</dt>
              <dd>The programming language used to build advanced Web sites and applications</dd>
            </dl>
            <h2>Inline HTML elements</h2>
            <p>HTML defines a long list of available inline tags, a complete list of which can be found on the <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element">Mozilla Developer Network</a>.</p>
            <ul>
              <li><strong>To bold text</strong>, use <code class="language-plaintext highlighter-rouge">&lt;strong&gt;</code>.</li>
              <li><em>To italicize text</em>, use <code class="language-plaintext highlighter-rouge">&lt;em&gt;</code>.</li>
              <li>Abbreviations, like <abbr title="HyperText Markup Langage">HTML</abbr> should use <code class="language-plaintext highlighter-rouge">&lt;abbr&gt;</code>, with an optional <code class="language-plaintext highlighter-rouge">title</code> attribute for the full phrase.</li>
              <li>Citations, like <cite>— Mark Otto</cite>, should use <code class="language-plaintext highlighter-rouge">&lt;cite&gt;</code>.</li>
              <li><del>Deleted</del> text should use <code class="language-plaintext highlighter-rouge">&lt;del&gt;</code> and <ins>inserted</ins> text should use <code class="language-plaintext highlighter-rouge">&lt;ins&gt;</code>.</li>
              <li>Superscript <sup>text</sup> uses <code class="language-plaintext highlighter-rouge">&lt;sup&gt;</code> and subscript <sub>text</sub> uses <code class="language-plaintext highlighter-rouge">&lt;sub&gt;</code>.</li>
            </ul>
            <p>Most of these elements are styled by browsers with few modifications on our part.</p>
            <h2>Heading</h2>
            <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
            <h3>Sub-heading</h3>
            <p>This is some additional paragraph placeholder content. It has been written to fill the available space and show how a longer snippet of text affects the surrounding content. We'll repeat it often to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
            <pre><code>Example code block</code></pre>
            <p>This is some additional paragraph placeholder content. It's a slightly shorter version of the other highly repetitive body text used throughout.</p> -->
          </article>
          <nav class="blog-pagination" aria-label="Pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
          </nav>
    
        </div>
    
        <div class="col-md-4">
          <div class="position-sticky" style="top: 2rem;">
            <div class="p-4 mb-3 bg-light rounded">
              <h4 class="fst-italic">About</h4>
              <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
            </div>
          </div>
        </div>
      </div>
</main>
{% endblock %}

templates/blog/blog_home.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <!--Section for random post -->
    {% if post.image.url %}
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark" style="background-image: url('{{post.image.url}}'); background-size: cover;">
    {% endif %}
      <div class="col-md-6 px-0">
        <a href="{% url 'blog:blog_detail' post.slug %}" style="color: white; text-decoration: none; "> <h1 class="display-4 fst-italic">{{post.title|slice:':50'}}..</h1> </a>
        <p class="lead my-3">{{post.content|slice:':150'}}</p>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-md-6">
        <!-- Section for the recent post -->
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success">{{recent_post.tag}}</strong>
            <a href="{% url 'blog:blog_detail' recent_post.slug %}" style="color: #000; text-decoration:none"> 
              <h3 class="mb-0">{{recent_post.title|slice:':65'}}..</h3>
            </a>
            <div class="mb-1 text-muted">{{recent_post.created_at}}</div>
            <p class="mb-auto">{{recent_post.content|slice:':150'}}</p>
          </div>
          </div>
      </div>
      <div class="col-md-6">
        <!-- Section for the first post of all time -->
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">{{older_post.tag}}</strong>
            <a href="{% url 'blog:blog_detail' older_post.slug %}" style="color: #000; text-decoration:none">
              <h3 class="mb-0">{{older_post.title|slice:':65'}}..</h3>
            </a>
            <div class="mb-1 text-muted">{{older_post.created_at}}</div>
            <p class="card-text mb-auto">{{older_post.content|slice:':150'}}</p>
          </div>
          </div>
      </div>
    </div>
  
    <div class="row g-5">
      <div class="col-md-8">
        <hr>
        <!-- List of post filtered by only 3 results -->
        <article class="blog-post">
          {% for news in news_posts %}
            <h2 class="blog-post-title">
                <a href="{% url 'blog:blog_detail' news.slug %}" style="color: black;         text-decoration: none;" >{{news.title}}
                </a> 
            </h2>
            <p class="blog-post-meta"> Posted on: {{news.created_at}}
              Written by: 
                <a href="" style="color: rgb(71, 71, 71); text-decoration: none; ">
                  {{news.author}}
                <a>
            </p>
            <p>{{news.sub_title}}</p>
            <hr>
            <p>{{news.content|slice:':400'}}</p>
            <br> 
            <br>
          </article> 
          {% endfor %}
        <nav class="blog-pagination" aria-label="Pagination">
          
            <a class="btn btn-outline-primary" href=" url 'blog:blog_list' older.slug %}">Older</a>
         
            <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
        </nav>
      </div>
      <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
          <div class="p-4 mb-3 bg-light rounded">
            <h4 class="fst-italic">Our authors</h4>
            {% for author in authors %}
                <p class="mb-0">{{author.username}}</p>
            {% endfor %}
          </div>
          <div class="p-4">
            <!-- Archives for years -->
            <h4 class="fst-italic">Archives</h4>
            {% for obj in filtered_objects %}
              <ol class="list-unstyled mb-0">
                <li><a href="{% url 'blog:archives_list' year=obj.month_year.year %}" style="color: #000; text-decoration:none " >{{ obj.month_year|date:"F Y" }}</a></li>
              </ol>
            {% endfor %}
            </div>
        </div>
      </div>
    </div>
  
  </main>
{% endblock %}

templates/blog/blog_list.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
<div class="row g-5">
    <div class="col-md-8">
      <hr>
      <article class="blog-post">
        {% for blog in posts %}
          <h2 class="blog-post-title">
              <a href="{% url 'blog:blog_detail' blog.slug %}" style="color: black; text-decoration: none;" >{{blog.title}}</a> </h2>
          <p class="blog-post-meta">{{blog.created_at}}<a href="#" style="color: black; text-decoration: none;"></a> Author: {{blog.author}} | {{blog.tag}}</p>
          <p>{{blog.sub_title}}</p>
          <hr>
          <p>{{blog.content|slice:':600'}}</p>
          <br> 
          <br>
        {% endfor %}
      </article> 
      <nav class="blog-pagination" aria-label="Pagination">
        
          <a class="btn btn-outline-primary" href="">Older</a>
       
          <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>
    </div>
</div>
</main>
{% endblock %}

templates/blog/search_results.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
<div class="row g-5">
    <div class="col-md-8">
      <hr>
      <article class="blog-post">
        <div class="d-flex justify-content-start">
          <form class="mr-3" action="{% url 'blog:search_results' %}" method="GET">
              <input class="form-control form-control-sm" type="text" name="query" placeholder="Search">
              <button class="btn btn-sm btn-outline-secondary" type="submit">Search</button>
          </form>
        </div>
        <br>
        {% if query %}
          <h2>Search Results for "{{ query }}"</h2>
          <ul>
            {% for post in results %}
            <a href="{% url 'blog:blog_detail' post.slug %}" style="color: black; text-decoration: none;"><li>{{ post.title }}</li</a>  >
            <br>
            {% empty %}
              <li>No results found.</li>
            {% endfor %}
          </ul>
        {% else %}
          <p>Please enter a search query.</p>
        {% endif %}
      </article> 
      
    </div>
</div>
</main>
{% endblock %}