blog/urls.py
from django.urls import path

from .views import (BlogHomeView, 
                    PostDetailView, 
                    PostCreate, 
                    BlogListView, 
                    ArchivesListView,
                    PostDeleteView, 
                    PostUpdateView)
from . import views

app_name='blog'


urlpatterns = [
    path('subscribe/', views.subscribe, name='subs'),
    path('search/', views.search_results, name='search_results'),

    path('comment/edit/<int:pk>/', views.comment_edit, name='comment_edit'),
    path('comment/delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),

    path('archives/<int:year>/', ArchivesListView.as_view(), name='archives_list'),
    path('', BlogHomeView.as_view(), name='blog_home'),
    path('tag/<str:tag>/', BlogListView.as_view(), name='blog_list'),

    path('detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('add_post/', PostCreate.as_view(), name='add_post'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete_post'),
    path('update/<slug:slug>/', PostUpdateView.as_view(), name='update_post'),
]

profiles/urls.py
from django.urls import path

from .views import UserSignUpView, UserLoginView, UserLogoutView, UserDetailView

app_name='profile'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='profile_login'),
    path('signup/', UserSignUpView.as_view(), name='profile_signup'),
    path('logout/', UserLogoutView.as_view(), name='profile_logout'),
    path('user/<str:username>/', UserDetailView.as_view(), name='user_detail'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <title>T-S-P</title>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    
  </head>
  <body>
    
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <!-- Subscribe button -->
      <div class="col-4 pt-1">
        {% if user.is_authenticated %}
          <a class="link-secondary" href="{% url 'blog:subs' %}">Subscribe</a>
        {% endif %}
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="{% url 'blog:blog_home' %}">The Super Blog</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        {% if user.is_authenticated %}
          <!-- Add button -->
          <a href="{% url 'blog:add_post' %}" style="margin-right: 20px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black" class="bi bi-plus-square-dotted" viewBox="0 0 16 16">
              <path d="M2.5 0c-.166 0-.33.016-.487.048l.194.98A1.51 1.51 0 0 1 2.5 1h.458V0H2.5zm2.292 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zm1.833 0h-.916v1h.916V0zm1.834 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zM13.5 0h-.458v1h.458c.1 0 .199.01.293.029l.194-.981A2.51 2.51 0 0 0 13.5 0zm2.079 1.11a2.511 2.511 0 0 0-.69-.689l-.556.831c.164.11.305.251.415.415l.83-.556zM1.11.421a2.511 2.511 0 0 0-.689.69l.831.556c.11-.164.251-.305.415-.415L1.11.422zM16 2.5c0-.166-.016-.33-.048-.487l-.98.194c.018.094.028.192.028.293v.458h1V2.5zM.048 2.013A2.51 2.51 0 0 0 0 2.5v.458h1V2.5c0-.1.01-.199.029-.293l-.981-.194zM0 3.875v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 5.708v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 7.542v.916h1v-.916H0zm15 .916h1v-.916h-1v.916zM0 9.375v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .916v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .917v.458c0 .166.016.33.048.487l.98-.194A1.51 1.51 0 0 1 1 13.5v-.458H0zm16 .458v-.458h-1v.458c0 .1-.01.199-.029.293l.981.194c.032-.158.048-.32.048-.487zM.421 14.89c.183.272.417.506.69.689l.556-.831a1.51 1.51 0 0 1-.415-.415l-.83.556zm14.469.689c.272-.183.506-.417.689-.69l-.831-.556c-.11.164-.251.305-.415.415l.556.83zm-12.877.373c.158.032.32.048.487.048h.458v-1H2.5c-.1 0-.199-.01-.293-.029l-.194.981zM13.5 16c.166 0 .33-.016.487-.048l-.194-.98A1.51 1.51 0 0 1 13.5 15h-.458v1h.458zm-9.625 0h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zm1.834-1v1h.916v-1h-.916zm1.833 1h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
            </svg>
          </a>
        
          <!-- Search button -->
          <a href="{% url 'blog:search_results' %}" style="margin-right: 10px;"> 
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg>
          </a>
        {% else %}
          <!-- Blank -->
        {% endif %}
        <br>

          {% if user.is_authenticated %}
              <a class="btn btn - primary" href="{% url 'profile:user_detail' username=user %}">{{user.first_name}}</a>
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'profile:profile_logout' %}">Log out</a>
            {% else %}
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'profile:profile_signup' %}">Sign up</a>
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'profile:profile_login' %}">Log in</a>
          {% endif %} 
      </div>
    </div>
  </header>

  
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      {% for tag in tags %}
        <a class="p-2 link-secondary" href="{% url 'blog:blog_list' tag=tag %}">{{tag}}</a>
      {% endfor %}
    </nav>
  </div>
</div>

{% block content %}
  
{% endblock %}

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>


    
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}

<main class="container" style="padding: 100px;">
    <h2 style="text-align: center;">Welcome to our Blog, feel free to talk and share.</h2>
    <p style="text-align: center;">We are people who like to talk and share our experience.</p>
</main>

{% endblock %}